Add possibility to use either /usr/bin/cu nor /usr/local/bin/cu-loop
Signed-off-by: Fabrice Dreux <fdreux@baylibre.com>

diff --git a/scripts/lab-setup/cu-loop b/scripts/lab-setup/cu-loop
--- a/scripts/lab-setup/cu-loop
+++ b/scripts/lab-setup/cu-loop
@@ -2,10 +2,17 @@
 DEV=$1
 BAUD=${2:-115200}
 
-CU=/usr/local/bin/cu
-#CU=/usr/bin/cu
+CU_LOCAL=/usr/local/bin/cu
+CU_MAIN=/usr/bin/cu
 
-test -e $CU || echo "ERROR $CU no such file";exit 1
+if [ -e $CU_LOCAL ];then
+    CU=$CU_LOCAL
+elif [ -e $CU_MAIN ];then
+    CU=$CU_MAIN
+else
+    echo "ERROR no such file $CU_LOCAL or $CU_MAIN"
+    exit 1
+fi
 
 while true; do
   #
@@ -18,7 +25,10 @@ while true; do
       test -e $DEV && $CU -l $DEV -s $BAUD --parity=none --nostop --nortscts dir
   fi
 
-  test $? -ne 0 && echo "ERROR during cu-loop execution";exit 1
+  if [ $? -ne 0 ];then
+      echo "ERROR during cu-loop execution"
+      exit 1
+  fi
 
   sleep 0.5
 done
